version: "3.9"

services:
  react:
    image: matheusserafim/react-locadora:2.0
    container_name: react-app
    ports:
      - "5173:5173"
    depends_on:
      - spring
    restart: always
    networks:
      - public_network

  spring:
    image: matheusserafim/spring-boot-locadora:1.0
    container_name: spring
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
    restart: always
    networks:
      - public_network
      - private_network

  db_postgres:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loc001
    restart: always
    networks:
      - private_network

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db_postgres
    restart: always
    networks:
      - public_network
      - private_network

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
